version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "csdj92"
    reviewers:
      - "csdj92"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      # Group React-related updates
      react-updates:
        patterns:
          - "react*"
          - "@types/react*"
      # Group Electron-related updates
      electron-updates:
        patterns:
          - "electron*"
          - "@electron*"
      # Group ESLint-related updates
      eslint-updates:
        patterns:
          - "eslint*"
          - "@eslint*"
      # Group Vite-related updates
      vite-updates:
        patterns:
          - "vite*"
          - "@vitejs*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "csdj92"
    reviewers:
      - "csdj92"
    commit-message:
      prefix: "ci" 