# .github/workflows/build-and-release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'          # e.g. v0.0.3
  workflow_dispatch:       # allow manual reruns

permissions:
  contents: write
  packages: write           # required if you ever publish to GH Packages

jobs:
  build:
    runs-on: windows-latest

    # Make the token available to every step (electron-forge reads env.GITHUB_TOKEN)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1- Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # 2- Verify tag = package.json version
      - name: Verify version tag
        shell: bash
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          PKG_VERSION=$(jq -r .version package.json)
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "::error::Tag version ($TAG_VERSION) doesn't match package.json ($PKG_VERSION)"
            exit 1
          fi

      # 3- Install Node (with npm cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 4- Install Python (with pip cache) – needed for your DB-build script

      # 4- Restore Node deps
      - name: Install Node dependencies
        run: npm ci

      # 5- Build renderer bundle
      - name: Build React app
        run: npm run build

      # 6- Package the Electron app (creates installers/zips in `out/`)
      - name: Make Electron distributables
        run: npm run make:complete

      # 7- Publish → creates/updates GitHub Release & uploads artifacts
      - name: Publish Electron app to GitHub Release
        run: npm run publish
