# .github/workflows/build-and-release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'          # e.g. v0.0.3
  workflow_dispatch:       # allow manual reruns

permissions:
  contents: write
  packages: write           # required if you ever publish to GH Packages

jobs:
  build:
    runs-on: windows-latest

    # Make the token available to every step (electron-forge reads env.GITHUB_TOKEN)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # 1- Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # 2- Clean up workspace
      - name: Clean workspace
        shell: powershell
        run: |
          # Clean up any existing temp files
          if (Test-Path "$env:TEMP\electron-packager") {
            Remove-Item "$env:TEMP\electron-packager" -Recurse -Force -ErrorAction SilentlyContinue
          }
          # Clean up any existing out directory
          if (Test-Path "out") {
            Remove-Item "out" -Recurse -Force -ErrorAction SilentlyContinue
          }

      # 3- Fix file permissions
      - name: Fix file permissions
        shell: powershell
        run: |
          # Remove read-only attributes from all files
          Get-ChildItem -Recurse | ForEach-Object { 
            try {
              $_.Attributes = $_.Attributes -band (-bnot [System.IO.FileAttributes]::ReadOnly)
            } catch {
              Write-Warning "Could not modify attributes for: $($_.FullName)"
            }
          }
          # Ensure package.json is writable
          if (Test-Path "package.json") {
            $file = Get-Item "package.json"
            $file.Attributes = $file.Attributes -band (-bnot [System.IO.FileAttributes]::ReadOnly)
            Write-Host "package.json attributes: $($file.Attributes)"
          }

      # 4- Verify tag = package.json version
      - name: Verify version tag
        shell: bash
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          PKG_VERSION=$(node -pe "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
          echo "Tag version: $TAG_VERSION"
          echo "Package version: $PKG_VERSION"
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "::error::Tag version ($TAG_VERSION) doesn't match package.json ($PKG_VERSION)"
            exit 1
          fi

      # 5- Install Node (with npm cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 6- Verify database exists
      - name: Verify database exists
        shell: powershell
        run: |
          if (Test-Path "Database/database.sqlite") {
            $dbSize = (Get-Item "Database/database.sqlite").Length / 1MB
            Write-Host "✓ Database found: $([math]::Round($dbSize, 2)) MB"
          } else {
            Write-Error "✗ Database not found at Database/database.sqlite"
            exit 1
          }

      # 7- Restore Node deps
      - name: Install Node dependencies
        run: npm ci

      # 8- Build complete application with resources (matches local build process)
      - name: Build complete application with resources
        env:
          DEBUG: electron-forge:*
        run: npm run build:complete

      # 9- Verify packaged output
      - name: Verify packaged output
        shell: powershell
        run: |
          # Check if the packaged app exists
          if (Test-Path "out/desktopmtg-win32-x64") {
            Write-Host "✓ Packaged app found"
            
            # Check if database was packaged
            if (Test-Path "out/desktopmtg-win32-x64/resources/Database/database.sqlite") {
              $dbSize = (Get-Item "out/desktopmtg-win32-x64/resources/Database/database.sqlite").Length / 1MB
              Write-Host "✓ Database packaged: $([math]::Round($dbSize, 2)) MB"
            } else {
              Write-Error "✗ Database not found in packaged app"
              exit 1
            }
            
            # Check if HTML files were packaged
            if (Test-Path "out/desktopmtg-win32-x64/resources/dist/index.html") {
              Write-Host "✓ HTML files packaged"
            } else {
              Write-Error "✗ HTML files not found in packaged app"
              exit 1
            }
            
            # Calculate total size
            $totalSize = (Get-ChildItem -Path "out/desktopmtg-win32-x64" -Recurse | Measure-Object -Property Length -Sum).Sum / 1GB
            Write-Host "📦 Total packaged size: $([math]::Round($totalSize, 2)) GB"
          } else {
            Write-Error "✗ Packaged app not found"
            exit 1
          }

      # 10- Create distributables (installers)
      - name: Create distributables
        env:
          DEBUG: electron-forge:*
        run: npm run make

      # 11- Publish → creates/updates GitHub Release & uploads artifacts
      - name: Publish Electron app to GitHub Release
        run: npm run publish
